### ISSUE TITLE
[V2 UI]: Update responsive layout sizing

### ISSUE THREAD

**Issue by jacksonjacobs1** [choosehappy/HistoQC#282]
The HistoQC V2 UI should fit into a browser window on most screens. This requires the following changes:

- [x] Enforce responsive dimensions, by means of either bootstrap responsive component classes or responsive CSS
- [x] Decrease slickgrid height
- [x] Decrease parcoords height
- [x] Decrease scatter plot height

**Comment by jacksonjacobs1** [comment]
fixed in https://github.com/choosehappy/HistoQC/commit/f440a0017d150be72585cd486912b6b886f488fb
